use clap::{Parser, Subcommand, ValueEnum};
use laverna::prelude::*;
use laverna::strategy::{synthesize_strategy, StrategyReport};

// Compiled-in seed corpus (generated by build.rs). Embedded unconditionally so
// the binary is self-contained from any CWD — fixes T35.
include!(concat!(env!("OUT_DIR"), "/embedded.rs"));
use serde_json::Value;
use std::borrow::Cow;
use std::io::{BufRead, Write};

/// Output format selector for machine-readable (`json`) vs human (`text`) output.
#[derive(Clone, Copy, Debug, PartialEq, Eq, ValueEnum)]
enum OutputFormat {
    Text,
    Json,
}

#[derive(Parser)]
#[command(
    name = "laverna",
    about = "Laverna — deterministic Vedic reasoning engine",
    long_about = "Laverna maps a question onto the 9-graha wheel and reasons \
back down to proof (NAND-to-bankai). It never guesses: out-of-scope input fails \
loudly instead of hallucinating.",
    version,
    after_long_help = "EXAMPLES:\n  laverna ping\n  laverna solve --query \"2 + 3 = 5\"\n  laverna solve --query \"10 % 3 = 1\" --format json\n  laverna solve --batch < queries.jsonl\n  laverna route --query \"how should we architect for LLM safety?\" --format json\n  laverna chart -d \"1994-04-14 20:09\" --latitude 45.4 --longitude -92.9 --format json\n  laverna validate \"2 + 3 = 5\" --format json\n  laverna formulas --domain health"
)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Health check (prints "pong")
    Ping,
    /// Show version and enabled features
    Info,
    /// Full reasoning pipeline: descent → formula → Tanto evaluation
    Solve {
        /// Natural-language or structured query (omit with --batch to read stdin)
        #[arg(short, long)]
        query: Option<String>,
        /// Verbose output with provenance chains
        #[arg(short, long)]
        verbose: bool,
        /// Richer trace: per-token graha decomposition + provenance chains
        #[arg(long)]
        explain: bool,
        /// Output format: text (default) or json
        #[arg(long, value_enum, default_value_t = OutputFormat::Text)]
        format: OutputFormat,
        /// Read queries from stdin (JSONL `{"query": "..."}` or one per line); emits JSONL
        #[arg(long)]
        batch: bool,
    },
    /// Reverse-route a query to a strategy via the 9-graha wheel
    Route {
        /// Natural-language query to turn into a strategy
        #[arg(short, long)]
        query: Option<String>,
        /// Comma-separated repo list to turn into an assimilation playbook
        #[arg(short = 'R', long = "repos")]
        repos: Option<String>,
        /// Show the per-token graha decomposition
        #[arg(short, long)]
        verbose: bool,
        /// Richer trace: always show the per-token graha decomposition
        #[arg(long)]
        explain: bool,
        /// Output format: text (default) or json
        #[arg(long, value_enum, default_value_t = OutputFormat::Text)]
        format: OutputFormat,
    },
    /// Look up an archetypal seed entity by ID
    EntityGet {
        /// Entity ID (e.g., "shukra", "bipolar_disorder")
        entity_id: String,
    },
    /// Cast a Vedic birth chart (lagna + 12 bhavas) for a datetime + location
    Chart {
        /// ISO datetime: YYYY-MM-DD HH:MM:SS
        #[arg(short, long)]
        datetime: String,
        /// Location name (optional, resolves lagna + bhavas)
        #[arg(short, long)]
        location: Option<String>,
        /// Observer latitude in degrees (N positive) for lagna + bhavas
        #[arg(long, allow_hyphen_values = true)]
        latitude: Option<f64>,
        /// Observer longitude in degrees (E positive) for lagna + bhavas
        #[arg(long, allow_hyphen_values = true)]
        longitude: Option<f64>,
        /// Richer trace: print the graha aspect matrix
        #[arg(long)]
        explain: bool,
        /// Output format: text (default) or json
        #[arg(long, value_enum, default_value_t = OutputFormat::Text)]
        format: OutputFormat,
    },
    /// Verify a Tanto formula expression
    Validate {
        /// Expression to validate (e.g., "2 + 3 = 5")
        expression: String,
        /// Output format: text (default) or json
        #[arg(long, value_enum, default_value_t = OutputFormat::Text)]
        format: OutputFormat,
    },
    /// List loaded formulas (optionally filtered by domain)
    Formulas {
        /// Filter by domain keyword
        #[arg(short, long)]
        domain: Option<String>,
        /// Max results
        #[arg(short, long, default_value = "20")]
        limit: usize,
    },
    /// List loaded seed entities (optionally filtered)
    Entities {
        /// Filter by keyword
        #[arg(short, long)]
        filter: Option<String>,
        /// Filter by graha domain (e.g. "surya", "rahu")
        #[arg(short = 'D', long = "domain")]
        domain: Option<String>,
        /// Max results
        #[arg(short, long, default_value = "20")]
        limit: usize,
    },
    /// Solve a domain-agnostic stat/point-allocation optimization from a schema
    Optimize {
        /// Path to the TOML optimization schema
        #[arg(short, long)]
        schema: String,
        /// Return N distinct Pareto-optimal allocations
        #[arg(short = 'K', long = "top-k", default_value = "1")]
        top_k: usize,
        /// Dump the per-item marginal-value trace for each solution
        #[arg(short, long)]
        explain: bool,
    },
    /// Print the canonical TOML template for a subcommand's input (self-describing)
    Schema {
        /// Schema name: optimize
        name: String,
    },
    /// Start MCP JSON-RPC server on stdin/stdout
    #[cfg(feature = "mcp")]
    Mcp,
    /// Run web search (World Bank stats)
    #[cfg(feature = "websearch")]
    Websearch {
        /// Search query
        query: String,
    },
}

fn main() {
    let cli = Cli::parse();

    match cli.command {
        Commands::Ping => println!("pong"),
        Commands::Info => {
            let formula_reg = load_formula_registry();
            let entity_reg = load_entity_registry();
            println!("laverna {}", env!("CARGO_PKG_VERSION"));
            println!("edition 2021");
            let features = collect_features();
            println!("features: {features}");
            println!("formulas: {}", formula_reg.len());
            println!("entities: {}", entity_reg.seed_count());
            let mut by_domain: std::collections::BTreeMap<String, usize> =
                std::collections::BTreeMap::new();
            for id in entity_reg.list_seeds() {
                if let Some(seed) = entity_reg.get_seed_ref(id) {
                    let key = seed
                        .dominant_graha()
                        .map(|g| g.name().to_string())
                        .unwrap_or_else(|| "ungrouped".to_string());
                    *by_domain.entry(key).or_insert(0) += 1;
                }
            }
            println!("entity domains (graha classification):");
            for (d, n) in &by_domain {
                println!("  {d}: {n}");
            }
        }
        Commands::Solve {
            query,
            verbose,
            explain,
            format,
            batch,
        } => {
            if batch {
                cmd_solve_batch(verbose, explain);
            } else if let Some(q) = query {
                let result = run_solve(&q);
                print_solve(&result, verbose, explain, format);
            } else {
                eprintln!("error: `solve` requires --query <Q> or --batch");
                std::process::exit(2);
            }
        }
        Commands::Route {
            query,
            repos,
            verbose,
            explain,
            format,
        } => match (query, repos) {
            (_, Some(repos_csv)) => cmd_route_repos(&repos_csv, verbose, explain, format),
            (Some(query), None) => {
                let result = run_route(&query);
                print_route(&result, verbose, explain, format);
            }
            (None, None) => {
                eprintln!("error: `route` requires --query <Q> or --repos <a,b,c>");
                std::process::exit(2);
            }
        },
        Commands::EntityGet { entity_id } => cmd_entity_get(&entity_id),
        Commands::Chart {
            datetime,
            location,
            latitude,
            longitude,
            explain,
            format,
        } => cmd_chart(
            &datetime,
            location.as_deref(),
            latitude,
            longitude,
            explain,
            format,
        ),
        Commands::Validate { expression, format } => cmd_validate(&expression, format),
        Commands::Formulas { domain, limit } => cmd_formulas(domain.as_deref(), limit),
        Commands::Entities {
            filter,
            domain,
            limit,
        } => cmd_entities(filter.as_deref(), domain.as_deref(), limit),
        Commands::Optimize {
            schema,
            top_k,
            explain,
        } => cmd_optimize(&schema, top_k, explain),
        Commands::Schema { name } => cmd_schema(&name),
        #[cfg(feature = "mcp")]
        Commands::Mcp => cmd_mcp(),
        #[cfg(feature = "websearch")]
        Commands::Websearch { query } => cmd_websearch(&query),
    }
}

// ─── Feature Detection ──────────────────────────────────────────────────────

fn collect_features() -> &'static str {
    let mut features = Vec::new();
    if cfg!(feature = "mcp") {
        features.push("mcp");
    }
    if cfg!(feature = "websearch") {
        features.push("websearch");
    }
    if cfg!(feature = "budget") {
        features.push("budget");
    }
    if cfg!(feature = "llm") {
        features.push("llm");
    }
    // Seed corpus is always embedded in the binary (T35) — surfaced for transparency.
    features.push("embedded-corpus");
    if cfg!(feature = "bench") {
        features.push("bench");
    }
    if features.is_empty() {
        "none (minimal)"
    } else {
        Box::leak(features.join(", ").into_boxed_str())
    }
}

// ─── Data Loading ───────────────────────────────────────────────────────────
//
// The seed corpus (formulas, synonyms, entities, nonmath, shikai forms, events)
// is compiled into the binary by `build.rs` (embedded.rs) and loaded here. This
// makes the binary self-contained: it returns the full corpus from any working
// directory, fixing T35 (entities/formulas previously only loaded when run from
// the repo root).

fn load_formula_registry() -> FormulaRegistry {
    let mut reg = FormulaRegistry::new();
    // Embedded `[[formula]]` corpus + search synonyms. NONMATH_TOML holds
    // `[[grammar]]` tables, which the formula registry ignores (harmless no-op
    // here, but keeps the embedded corpus available should grammar support land).
    let _ = reg.load_from_toml_str(FORMULAS_TOML);
    let _ = reg.load_synonyms_from_str(SYNONYMS_TOML);
    let _ = reg.load_from_toml_str(NONMATH_TOML);
    reg
}

fn load_entity_registry() -> EntityRegistry {
    let mut reg = EntityRegistry::new();
    let _ = reg.load_seeds_from_str(ENTITIES_TOML);
    reg
}

fn load_shikai_forms() -> ShikaiFormRegistry {
    let mut forms = ShikaiFormRegistry::new();
    let _ = forms.load_from_str(SHIKAI_FORM_TOML);
    forms
}

fn load_events() -> EventRegistry {
    let mut events = EventRegistry::new();
    let _ = events.load_from_str(EVENTS_TOML);
    events
}

// ─── solve Command ──────────────────────────────────────────────────────────

/// Extract the longest contiguous arithmetic expression from a query, keeping
/// its operators so it can be evaluated with operator precedence (via the Tanto
/// parser `validate` uses) instead of naive pairwise number addition (T36).
/// Returns `None` when no numeric/operator run is present.
fn extract_arithmetic_expression(query: &str) -> Option<String> {
    let bytes = query.as_bytes();
    let is_op_char = |b: u8| {
        b.is_ascii_digit()
            || b == b'.'
            || matches!(
                b,
                b'+' | b'-' | b'*' | b'/' | b'%' | b'^' | b'(' | b')' | b'='
            )
            || b.is_ascii_whitespace()
    };
    let mut best_start: Option<usize> = None;
    let mut best_end: usize = 0;
    let mut best_len: usize = 0;
    let mut start: Option<usize> = None;
    let mut end_run = |s: usize, e: usize| {
        let len = e - s;
        if len > best_len {
            best_len = len;
            best_start = Some(s);
            best_end = e;
        }
    };
    for (i, &b) in bytes.iter().enumerate() {
        if is_op_char(b) {
            if start.is_none() {
                start = Some(i);
            }
        } else if let Some(s) = start.take() {
            end_run(s, i);
        }
    }
    if let Some(s) = start.take() {
        end_run(s, bytes.len());
    }
    best_start
        .map(|s| {
            let mut expr: String = query[s..best_end].trim().to_string();
            while matches!(
                expr.bytes().last(),
                Some(b'+' | b'*' | b'/' | b'%' | b'^' | b'=')
            ) {
                expr.pop();
            }
            while matches!(expr.bytes().next(), Some(b'+' | b'*' | b'/' | b'%' | b'=')) {
                expr.remove(0);
            }
            expr
        })
        .filter(|e| !e.is_empty() && e.chars().any(|c| c.is_ascii_digit()))
}

/// A single operator-expression evaluation result for JSON/text output.
struct NumExpr {
    expr: String,
    lhs_value: Option<f64>,
    stated_rhs: Option<f64>,
    matches: Option<bool>,
}

/// Fully-computed `solve` result — rendered as text or JSON without recomputation.
struct SolveResult {
    query: String,
    intent: &'static str,
    domain: &'static str,
    numerical: Vec<f64>,
    matrix: SettlingMatrix,
    tanto_evals: Vec<(String, String, Option<f64>)>,
    num_exprs: Vec<NumExpr>,
    provenance: Vec<(String, Vec<ProvenanceStep>)>,
}

/// Run the full `solve` pipeline and collect every result field.
fn run_solve(query: &str) -> SolveResult {
    let formula_reg = load_formula_registry();
    let entity_reg = load_entity_registry();
    let forms = load_shikai_forms();
    let events = load_events();

    let descent_engine = DescentEngine::new(formula_reg.clone(), entity_reg.clone(), forms, events);

    let intent = parse_query_intent(query);
    let domain = determine_query_domain(query);
    let numerical = extract_numerical_values(query);

    let matrix = descent_engine.descend(query);

    let env = create_env();
    let mut tanto_evals = Vec::new();
    for token in &matrix.tokens {
        if let Some(ref expr) = token.formal_expression {
            let val = evaluate_expr(expr, &env);
            tanto_evals.push((token.text.clone(), expr.clone(), val));
        }
    }

    let mut num_exprs = Vec::new();
    if numerical.len() >= 2 {
        if let Some(expr) = extract_arithmetic_expression(query) {
            if let Some(eq_pos) = expr.find('=') {
                let lhs = expr[..eq_pos].trim();
                let rhs = expr[eq_pos + 1..].trim();
                match (evaluate_expr(lhs, &env), rhs.parse::<f64>().ok()) {
                    (Some(l_val), Some(r_val)) => {
                        let matches = (l_val - r_val).abs() < 1e-9;
                        num_exprs.push(NumExpr {
                            expr: expr.clone(),
                            lhs_value: Some(l_val),
                            stated_rhs: Some(r_val),
                            matches: Some(matches),
                        });
                    }
                    (Some(l_val), None) => num_exprs.push(NumExpr {
                        expr: expr.clone(),
                        lhs_value: Some(l_val),
                        stated_rhs: None,
                        matches: None,
                    }),
                    _ => num_exprs.push(NumExpr {
                        expr: expr.clone(),
                        lhs_value: None,
                        stated_rhs: None,
                        matches: None,
                    }),
                }
            } else if let Some(val) = evaluate_expr(&expr, &env) {
                num_exprs.push(NumExpr {
                    expr: expr.clone(),
                    lhs_value: Some(val),
                    stated_rhs: None,
                    matches: None,
                });
            } else {
                num_exprs.push(NumExpr {
                    expr: expr.clone(),
                    lhs_value: None,
                    stated_rhs: None,
                    matches: None,
                });
            }
        }
    }

    let provenance = matrix
        .tokens
        .iter()
        .filter(|t| !t.provenance.is_empty())
        .map(|t| (t.text.clone(), t.provenance.clone()))
        .collect();

    SolveResult {
        query: query.to_string(),
        intent,
        domain,
        numerical,
        matrix,
        tanto_evals,
        num_exprs,
        provenance,
    }
}

/// Render `solve` as text or JSON.
fn print_solve(result: &SolveResult, verbose: bool, explain: bool, format: OutputFormat) {
    if format == OutputFormat::Json {
        let value = solve_to_json(result);
        println!("{}", serde_json::to_string(&value).unwrap());
        return;
    }

    println!("intent: {}", result.intent);
    println!("domain: {}", result.domain);
    if !result.numerical.is_empty() {
        println!("numerical: {:?}", result.numerical);
    }

    println!();
    println!(
        "descent: {:.0}% resolution, {:.2}/6 avg depth, {:.0}% NAND",
        result.matrix.resolution_score * 100.0,
        result.matrix.average_depth,
        result.matrix.nand_completeness() * 100.0,
    );

    for token in &result.matrix.tokens {
        let depth = token.settled_layer.depth();
        let layer = token.settled_layer.name();
        print!("  \"{}\" → {layer} (d{depth})", token.text);
        if !token.domains.is_empty() {
            let domains: Vec<_> = token.domains.iter().map(|d| format!("{d:?}")).collect();
            print!(", domains: [{}]", domains.join(", "));
        }
        if !token.formulas.is_empty() {
            print!(", formulas: {}", token.formulas.len());
        }
        if let Some(ref entity) = token.entity {
            print!(", entity: {entity}");
        }
        if let Some(ref formal) = token.formal_expression {
            print!(", formal: \"{formal}\"");
        }
        if token.is_absolute {
            print!(", NAND: absolute");
        }
        println!();
    }

    // Tanto math evaluation for formal expressions
    if !result.tanto_evals.is_empty() {
        println!();
        println!("tanto evaluations:");
        for (token, expr, val) in &result.tanto_evals {
            match val {
                Some(v) => println!("  {token} ({expr}) = {v:.4}"),
                None => println!("  {token} ({expr}) = error: evaluation failed"),
            }
        }
    }

    // Numerical evaluation
    if !result.num_exprs.is_empty() {
        println!();
        println!("numerical expressions:");
        for e in &result.num_exprs {
            match (e.lhs_value, e.stated_rhs, e.matches) {
                (Some(l), Some(r), Some(m)) => println!(
                    "  {} = {l:.4}  (stated RHS {r}: {})",
                    e.expr,
                    if m { "✓ match" } else { "✗ mismatch" }
                ),
                (Some(l), None, _) => println!("  {} = {l:.4}", e.expr),
                _ => println!("  {}: could not evaluate", e.expr),
            }
        }
    } else if result.numerical.len() >= 2 {
        println!();
        println!(
            "  (no operator expression present; scalars: {:?})",
            result.numerical
        );
    }

    // Richer trace: per-token graha decomposition (T46#4)
    if explain {
        println!();
        println!("graha decomposition:");
        for token in &result.matrix.tokens {
            let g = laverna::strategy::dominant_graha_of(token).map(|d| d.name().to_string());
            println!(
                "  \"{}\" → {}",
                token.text,
                g.unwrap_or_else(|| "—".to_string())
            );
        }
    }

    // Provenance (verbose or explain)
    if verbose || explain {
        println!();
        println!("provenance:");
        for (token, steps) in &result.provenance {
            println!("  \"{token}\" ({} steps):", steps.len());
            for (i, step) in steps.iter().enumerate() {
                match step {
                    ProvenanceStep::DomainClassification {
                        domain,
                        keyword,
                        confidence,
                    } => {
                        println!(
                            "    {}. DomainClassification: domain={keyword}→{domain}, conf={confidence:.1}",
                            i + 1
                        );
                    }
                    ProvenanceStep::FormulaMatch {
                        formula_id,
                        domain,
                        inputs,
                        output,
                    } => {
                        println!(
                            "    {}. FormulaMatch: {formula_id} [{domain}] {:?}→{output}",
                            i + 1,
                            inputs.as_slice()
                        );
                    }
                    ProvenanceStep::EntityMatch { entity_id, domain } => {
                        println!("    {}. EntityMatch: {entity_id} [{domain}]", i + 1);
                    }
                    ProvenanceStep::Unification {
                        formula_id,
                        entity_id,
                        bound_inputs,
                        ..
                    } => {
                        println!(
                            "    {}. Unification: formula={formula_id} entity={entity_id} bound={bound_inputs:?}",
                            i + 1
                        );
                    }
                    ProvenanceStep::FormalExpression { token, expression } => {
                        println!("    {}. FormalExpression: {token}=\"{expression}\"", i + 1);
                    }
                    ProvenanceStep::NandEvaluation {
                        gate,
                        inputs,
                        output,
                    } => {
                        println!("    {}. NandEvaluation: {gate}({inputs:?})={output}", i + 1);
                    }
                }
            }
        }
    }

    // Dominant domain summary
    if !result.matrix.dominant_domains.is_empty() {
        let domains: Vec<_> = result
            .matrix
            .dominant_domains
            .iter()
            .map(|d| format!("{d:?}"))
            .collect();
        println!();
        println!("dominant: [{}]", domains.join(", "));
    }
}

/// Build the JSON rendering of a `solve` result (self-describing for LLM callers).
fn solve_to_json(result: &SolveResult) -> Value {
    let mut tokens = serde_json::to_value(&result.matrix.tokens).unwrap();
    if let Value::Array(arr) = &mut tokens {
        for (i, tok_val) in arr.iter_mut().enumerate() {
            if let Some(tok) = result.matrix.tokens.get(i) {
                let graha = laverna::strategy::dominant_graha_of(tok).map(|d| d.name().to_string());
                if let Value::Object(o) = tok_val {
                    o.insert(
                        "dominant_graha".to_string(),
                        serde_json::to_value(&graha).unwrap(),
                    );
                }
            }
        }
    }
    let tanto: Vec<Value> = result
        .tanto_evals
        .iter()
        .map(|(tok, expr, val)| serde_json::json!({"token": tok, "expression": expr, "value": val}))
        .collect();
    let num_exprs: Vec<Value> = result
        .num_exprs
        .iter()
        .map(|e| {
            serde_json::json!({
                "expression": e.expr,
                "lhs_value": e.lhs_value,
                "stated_rhs": e.stated_rhs,
                "matches": e.matches
            })
        })
        .collect();
    let provenance: Vec<Value> = result
        .provenance
        .iter()
        .map(|(tok, steps)| serde_json::json!({"token": tok, "steps": steps}))
        .collect();
    serde_json::json!({
        "query": result.query,
        "intent": result.intent,
        "domain": result.domain,
        "numerical": result.numerical,
        "descent": {
            "resolution_score": result.matrix.resolution_score,
            "average_depth": result.matrix.average_depth,
            "nand_completeness": result.matrix.nand_completeness()
        },
        "tokens": tokens,
        "tanto_evaluations": tanto,
        "numerical_expressions": num_exprs,
        "provenance": provenance,
        "dominant_domains": result.matrix.dominant_domains
    })
}

/// Batch mode: read queries from stdin (JSONL `{"query": "..."}` or one per line)
/// and emit one JSON object per line (JSONL) — amortizes the registry load.
fn cmd_solve_batch(_verbose: bool, _explain: bool) {
    let stdin = std::io::stdin();
    let stdout = std::io::stdout();
    let mut out = stdout.lock();
    for line in stdin.lock().lines() {
        let line = match line {
            Ok(l) => l,
            Err(_) => break,
        };
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let query: String = if let Ok(v) = serde_json::from_str::<Value>(line) {
            v.get("query")
                .and_then(|q| q.as_str())
                .map(|s| s.to_string())
                .unwrap_or_else(|| line.to_string())
        } else {
            line.to_string()
        };
        let result = run_solve(&query);
        let value = solve_to_json(&result);
        let _ = writeln!(out, "{}", serde_json::to_string(&value).unwrap());
    }
}

// ─── route Command (reverse routing) ──────────────────────────────────────────

/// Build the descent matrix for a routing query using the same deterministic
/// pipeline as `cmd_solve`.
fn build_route_matrix(query: &str) -> SettlingMatrix {
    let formula_reg = load_formula_registry();
    let entity_reg = load_entity_registry();
    let forms = load_shikai_forms();
    let events = load_events();
    let descent_engine = DescentEngine::new(formula_reg, entity_reg, forms, events);
    descent_engine.descend(query)
}

/// Reverse-route result — rendered as text or JSON without recomputation.
struct RouteResult {
    query: String,
    report: StrategyReport,
    /// Per-token dominant graha force as `(symbol, name)`, or `None`.
    decomposition: Vec<(String, Option<(String, String)>)>,
}

/// Reverse-route a query to a strategy: descent → dominant graha forces →
/// synthesized action framework. Mirrors `cmd_solve`'s descent setup so the
/// strategy is grounded in the same deterministic pipeline.
fn run_route(query: &str) -> RouteResult {
    let matrix = build_route_matrix(query);
    let report: StrategyReport = synthesize_strategy(query, &matrix);
    let decomposition = matrix
        .tokens
        .iter()
        .map(|t| {
            let g = laverna::strategy::dominant_graha_of(t)
                .map(|d| (d.symbol().to_string(), d.name().to_string()));
            (t.text.clone(), g)
        })
        .collect();
    RouteResult {
        query: query.to_string(),
        report,
        decomposition,
    }
}

/// Render one graha `Domain` (or null) as a JSON object.
fn domain_value(g: Option<Domain>) -> Value {
    match g {
        Some(d) => serde_json::json!({
            "symbol": d.symbol(),
            "name": d.name(),
            "full_name": d.full_name(),
            "archetype": d.archetype(),
            "index": d.index()
        }),
        None => Value::Null,
    }
}

/// Render `route` as text or JSON.
fn print_route(result: &RouteResult, verbose: bool, explain: bool, format: OutputFormat) {
    if format == OutputFormat::Json {
        println!("{}", serde_json::to_string(&route_to_json(result)).unwrap());
        return;
    }

    println!("{}", result.report.format());

    if verbose || explain {
        println!();
        println!("decomposition (each token → dominant force):");
        for (token, g) in &result.decomposition {
            match g {
                Some((sym, name)) => println!("  \"{token}\" → {sym} ({name})"),
                None => println!("  \"{token}\" → (no graha force)"),
            }
        }
    }
}

/// Build the JSON rendering of a `route` result.
fn route_to_json(result: &RouteResult) -> Value {
    let forces: Vec<Value> = result
        .report
        .ranked
        .iter()
        .map(|(g, count, share)| {
            serde_json::json!({
                "symbol": g.symbol(),
                "name": g.name(),
                "full_name": g.full_name(),
                "archetype": g.archetype(),
                "index": g.index(),
                "hits": count,
                "share": share
            })
        })
        .collect();
    let decomposition: Vec<Value> = result
        .decomposition
        .iter()
        .map(|(token, g)| {
            serde_json::json!({"token": token, "symbol": g.as_ref().map(|(s, _)| s), "name": g.as_ref().map(|(_, n)| n)})
        })
        .collect();
    serde_json::json!({
        "query": result.query,
        "forces": forces,
        "primary": domain_value(result.report.primary),
        "secondary": domain_value(result.report.secondary),
        "tertiary": domain_value(result.report.tertiary),
        "decomposition": decomposition
    })
}

/// A known repo's assimilation profile: the descriptor drives the descent
/// (deterministic routing), the target/note are the researched mapping.
struct RepoProfile {
    name: Cow<'static, str>,
    descriptor: Cow<'static, str>,
    target: Cow<'static, str>,
    note: Cow<'static, str>,
}

/// Built-in profiles from the deep-dive of nutypebuddha's repositories.
fn repo_profile(name: &str) -> RepoProfile {
    match name.to_ascii_lowercase().as_str() {
        "athena-" => RepoProfile {
            name: Cow::Borrowed("Athena-"),
            descriptor: Cow::Borrowed(
                "harvest formulas and validation gates, preserve deterministic reasoning architecture and the four layer pipeline",
            ),
            target: Cow::Borrowed("Design source-of-truth"),
            note: Cow::Borrowed(
                "Laverna is its determinism-first reboot; harvest formulas + gate taxonomy",
            ),
        },
        "mana-core" => RepoProfile {
            name: Cow::Borrowed("mana-core"),
            descriptor: Cow::Borrowed(
                "run untrusted AI tasks in a sandbox with a full audit log, classify and plan safely without models",
            ),
            target: Cow::Borrowed("Sandbox + audit shape"),
            note: Cow::Borrowed(
                "Port WASM sandbox + audit log; replace ML classifier/planner with CID 5-gate validation",
            ),
        },
        "zanpakato" => RepoProfile {
            name: Cow::Borrowed("Zanpakato"),
            descriptor: Cow::Borrowed(
                "logic speed game with soul cards identity export truth engine",
            ),
            target: Cow::Borrowed("CID validation demo"),
            note: Cow::Borrowed("Truth-Engine → validation demo; identity/export metaphor"),
        },
        "mirror-sword" => RepoProfile {
            name: Cow::Borrowed("Mirror-Sword"),
            descriptor: Cow::Borrowed("reflection audit of decisions and archived outcomes"),
            target: Cow::Borrowed("Audit / reflection step"),
            note: Cow::Borrowed("Reflection/archive → CID reflection step metaphor"),
        },
        "zanpakato-kasien" => RepoProfile {
            name: Cow::Borrowed("Zanpakato-Kasien"),
            descriptor: Cow::Borrowed(
                "persona evolution hollow corruption time gated discipline and training",
            ),
            target: Cow::Borrowed("Discipline framing"),
            note: Cow::Borrowed(
                "Persona/hollow game → constraint-discipline framing (Shani)",
            ),
        },
        "soulsociety" => RepoProfile {
            name: Cow::Borrowed("SoulSociety"),
            descriptor: Cow::Borrowed("identity realm with access tiers and membership"),
            target: Cow::Borrowed("Identity / tier metaphor"),
            note: Cow::Borrowed("Identity realm → Zanpakuto access-tier metaphor"),
        },
        other => RepoProfile {
            name: Cow::Owned(other.to_string()),
            descriptor: Cow::Owned(other.to_string()),
            target: Cow::Borrowed("(generic — map via dominant force)"),
            note: Cow::Borrowed("No specific profile; routed by the wheel's dominant graha"),
        },
    }
}

/// Turn a comma-separated repo list into an assimilation playbook. Each repo is
/// reverse-routed through the same deterministic descent pipeline; the dominant
/// graha force decides its default ecosystem target when no specific profile exists.
fn cmd_route_repos(repos_csv: &str, verbose: bool, explain: bool, format: OutputFormat) {
    let repos: Vec<&str> = repos_csv
        .split(',')
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .collect();
    if repos.is_empty() {
        eprintln!("error: --repos requires a non-empty comma-separated list");
        std::process::exit(2);
    }

    let mut entries: Vec<Value> = Vec::new();
    for repo in repos {
        let profile = repo_profile(repo);
        let matrix = build_route_matrix(&profile.descriptor);
        let report = synthesize_strategy(&profile.descriptor, &matrix);

        let primary = report.primary;
        let target = profile.target;
        let default = primary
            .map(laverna::strategy::graha_default_target)
            .unwrap_or("—");

        let decomposition: Vec<Value> = if verbose || explain {
            matrix
                .tokens
                .iter()
                .map(|t| {
                    let g = laverna::strategy::dominant_graha_of(t)
                        .map(|d| (d.symbol().to_string(), d.name().to_string()));
                    serde_json::json!({"token": t.text, "symbol": g.as_ref().map(|(s, _)| s), "name": g.as_ref().map(|(_, n)| n)})
                })
                .collect()
        } else {
            Vec::new()
        };

        if format == OutputFormat::Json {
            entries.push(serde_json::json!({
                "repo": profile.name,
                "descriptor": profile.descriptor,
                "force": domain_value(primary),
                "target": target,
                "default_if_unknown": default,
                "note": profile.note,
                "decomposition": decomposition
            }));
            continue;
        }

        println!("● {}", profile.name);
        match primary {
            Some(g) => println!(
                "    force:  {} {} — {}",
                g.symbol(),
                g.name(),
                laverna::strategy::strategy_principle(g)
            ),
            None => println!("    force:  (no graha force resolved)"),
        }
        println!("    target: {}", target);
        println!("    default-if-unknown: {}", default);
        println!("    note:   {}", profile.note);

        if verbose || explain {
            println!("    decomposition:");
            for token in &matrix.tokens {
                match laverna::strategy::dominant_graha_of(token) {
                    Some(g) => println!("      \"{}\" → {} ({})", token.text, g.symbol(), g.name()),
                    None => println!("      \"{}\" → (no graha force)", token.text),
                }
            }
        }
        println!();
    }

    if format == OutputFormat::Json {
        println!(
            "{}",
            serde_json::to_string_pretty(&serde_json::json!({"playbook": entries})).unwrap()
        );
    } else {
        println!("Playbook is deterministic — identical repo lists yield identical maps.");
    }
}

// ─── entity-get Command ─────────────────────────────────────────────────────

fn cmd_entity_get(entity_id: &str) {
    let entity_reg = load_entity_registry();

    // Try seed lookup first
    if let Some(seed) = entity_reg.get_seed_ref(entity_id) {
        println!("id: {}", seed.id);
        println!("name: {}", seed.name);
        println!("description: {}", seed.description);
        if !seed.properties.is_empty() {
            println!("properties:");
            let mut props: Vec<_> = seed.properties.iter().collect();
            props.sort_by_key(|(k, _)| (*k).clone());
            for (key, value) in props {
                println!("  {key}: {value}");
            }
        }
        if !seed.constants.is_empty() {
            println!("constants:");
            let mut consts: Vec<_> = seed.constants.iter().collect();
            consts.sort_by_key(|(k, _)| (*k).clone());
            for (key, value) in consts {
                println!("  {key}: {value}");
            }
        }
        if !seed.tags.is_empty() {
            println!("tags: {:?}", seed.tags);
        }
        if let Some(ref formula) = seed.formula {
            println!("formula: {formula}");
        }
        if let Some(ref bija) = seed.bija {
            println!("bija: {bija}");
        }
        if let Some(ref mantra) = seed.mantra {
            println!("mantra: {mantra}");
        }
        if let Some(ref day) = seed.day {
            println!("day: {day}");
        }
        if !seed.ruled_nakshatras.is_empty() {
            println!("ruled_nakshatras: {:?}", seed.ruled_nakshatras);
        }
        return;
    }

    // Try search
    let results = entity_reg.search_seeds_ref(entity_id);
    if results.is_empty() {
        eprintln!("entity not found: {entity_id}");
        eprintln!("hint: try `laverna entities` to list all entities");
        std::process::exit(1);
    }

    println!("search results for \"{entity_id}\":");
    for seed in &results {
        println!("  {} — {}", seed.id, seed.description);
    }
}

// ─── chart Command ──────────────────────────────────────────────────────────

const GRAHA_NAMES: [&str; 9] = [
    "Surya",
    "Chandra",
    "Mangala",
    "Budha",
    "Brihaspati",
    "Shukra",
    "Shani",
    "Rahu",
    "Ketu",
];

/// Pure: validate observer coordinates are within Earth's geographic bounds.
fn validate_chart_coords(latitude: f64, longitude: f64) -> Result<(), String> {
    if !(-90.0..=90.0).contains(&latitude) {
        return Err(format!("latitude {latitude} out of range [-90, 90]"));
    }
    if !(-180.0..=180.0).contains(&longitude) {
        return Err(format!("longitude {longitude} out of range [-180, 180]"));
    }
    Ok(())
}

/// Built-in offline gazetteer for locations the user actually uses, then the
/// `xalen_houses` world-cities fallback. Deterministic; no network.
const GAZETTEER: &[(&str, f64, f64)] = &[
    ("Hinckley, MN", 46.0117, -92.9391),
    ("Hinckley, Minnesota", 46.0117, -92.9391),
    ("Hinckley", 46.0117, -92.9391),
    ("Minneapolis, MN", 44.9778, -93.2650),
    ("Minneapolis", 44.9778, -93.2650),
    ("St. Paul, MN", 44.9537, -93.0900),
    ("Duluth, MN", 46.7867, -92.1005),
    ("Pine City, MN", 45.8419, -92.9691),
    ("Sandstone, MN", 46.1283, -92.8652),
    ("Askov, MN", 46.1875, -92.7660),
];

/// Pure: resolve a city name to `(latitude, longitude)` in degrees.
fn geocode_city(name: &str) -> Option<(f64, f64)> {
    let query = name.trim().to_lowercase();
    for (city, latitude, longitude) in GAZETTEER {
        if city.to_lowercase() == query {
            return Some((*latitude, *longitude));
        }
    }
    xalen_houses::geocoding::city_coordinates(name).map(|g| (g.lat_deg(), g.lon_deg()))
}

fn cmd_chart(
    datetime: &str,
    location: Option<&str>,
    latitude: Option<f64>,
    longitude: Option<f64>,
    explain: bool,
    format: OutputFormat,
) {
    let dt = match parse_datetime(datetime) {
        Ok(dt) => dt,
        Err(e) => {
            eprintln!("error: {e}");
            std::process::exit(2);
        }
    };
    let jd = julian_day(
        dt.0 as i16,
        dt.1 as u8,
        dt.2 as u8,
        dt.3 as f64 + dt.4 as f64 / 60.0,
    );

    // Resolve observer coordinates (for lagna + bhavas).
    // Precedence: explicit --latitude/--longitude > --location city name.
    let coords: Option<(f64, f64)> = if let Some((lat, lon)) = latitude.zip(longitude) {
        if let Err(e) = validate_chart_coords(lat, lon) {
            eprintln!("error: {e}");
            std::process::exit(2);
        }
        Some((lat, lon))
    } else if let Some(loc) = location {
        match geocode_city(loc) {
            Some(g) => Some(g),
            None => {
                eprintln!("warning: unknown location '{loc}'; lagna and bhavas not computed");
                eprintln!("  use --latitude and --longitude for explicit coordinates");
                None
            }
        }
    } else {
        None
    };

    let date_str = format!("{}-{:02}-{:02} {:02}:{:02}", dt.0, dt.1, dt.2, dt.3, dt.4);
    let ayanamsa = lahiri_ayanamsa(jd);

    // Build ChartSnapshot (with location if resolved)
    let mut chart = ChartSnapshot::new(jd);
    if let Some((lat, lon)) = coords {
        chart = chart.with_location(lat, lon);
    }

    let personality = derive_personality(&chart);

    if format == OutputFormat::Json {
        let value = serde_json::json!({
            "julian_day": jd,
            "date": date_str,
            "ayanamsa": ayanamsa,
            "chart": serde_json::to_value(&chart).unwrap(),
            "personality": serde_json::to_value(&personality).unwrap()
        });
        println!("{}", serde_json::to_string_pretty(&value).unwrap());
        return;
    }

    println!("julian_day: {jd:.4}");
    println!("date: {date_str}");
    println!("ayanamsa (lahiri): {ayanamsa:.4}°");
    if coords.is_none() {
        println!("(no location given — lagna and bhavas omitted; ayanamsa is time-based, not location-based)");
    }

    // Print lagna
    if let Some(lagna) = chart.lagna {
        let extra = chart
            .ascendant_deg
            .map(|d| format!("  —  {d:.4}° sidereal"))
            .unwrap_or_default();
        println!("lagna: {} ({:?}){}", lagna.name(), lagna, extra);
    }

    // Print bhavas (house cusps)
    if !chart.house_cusps.is_empty() {
        println!();
        println!("bhavas:");
        for cusp in &chart.house_cusps {
            println!(
                "  {:>5}: {:>8.2}° {:10} ({})",
                cusp.house.name(),
                cusp.tropical,
                cusp.rashi.name(),
                cusp.house.domain(),
            );
        }
    }

    // Graha positions
    println!();
    println!("grahas:");
    for (i, name) in GRAHA_NAMES.iter().enumerate() {
        let gp = laverna::ephemeris::graha_position(Graha::from_index(i).unwrap(), jd);
        let degree_in_sign = gp.sidereal % 30.0;
        println!(
            "  {name:>12}: tropical {:>7.2}°, sidereal {:>7.2}° ({:?} {degree_in_sign:.2}°, nak {:?} pad {})",
            gp.tropical, gp.sidereal, gp.rashi, gp.nakshatra, gp.pada
        );
    }

    println!();
    println!("personality:");
    println!("  archetype: {:?}", personality.archetype);
    println!("  dominant: {:?}", personality.dominant);
    println!("  pillars: {:?}", personality.pillar_weights);

    if explain {
        println!();
        println!("aspect matrix (graha × graha):");
        for (i, row) in chart.aspect_matrix.iter().enumerate() {
            let name = GRAHA_NAMES.get(i).copied().unwrap_or("?");
            let cells: Vec<String> = row
                .iter()
                .map(|a| match a {
                    Some(asp) => format!("{asp:?}"),
                    None => ".".to_string(),
                })
                .collect();
            println!("  {name:>12}: {}", cells.join(" "));
        }
    }
}

fn parse_datetime(s: &str) -> Result<(i32, u32, u32, u32, u32), String> {
    let s = s.trim();
    if s.is_empty() {
        return Err("datetime is empty; expected YYYY-MM-DD HH:MM".to_string());
    }

    // Try "YYYY-MM-DD HH:MM" or "YYYY-MM-DD HH:MM:SS"
    let parts: Vec<&str> = s.split_whitespace().collect();
    let date_parts: Vec<u32> = parts[0].split('-').filter_map(|p| p.parse().ok()).collect();
    let time_parts: Vec<u32> = parts
        .get(1)
        .map(|t| t.split(':').filter_map(|p| p.parse().ok()).collect())
        .unwrap_or_default();

    let year = date_parts.first().copied().ok_or_else(|| {
        format!(
            "cannot parse year from '{}'; expected YYYY-MM-DD HH:MM",
            parts[0]
        )
    })? as i32;
    let month = date_parts.get(1).copied().ok_or_else(|| {
        format!(
            "cannot parse month from '{}'; expected YYYY-MM-DD HH:MM",
            parts[0]
        )
    })?;
    let day = date_parts.get(2).copied().ok_or_else(|| {
        format!(
            "cannot parse day from '{}'; expected YYYY-MM-DD HH:MM",
            parts[0]
        )
    })?;
    let hour = time_parts.first().copied().ok_or_else(|| {
        format!(
            "cannot parse hour from '{}'; expected HH:MM",
            parts.get(1).unwrap_or(&"")
        )
    })?;
    let minute = time_parts.get(1).copied().unwrap_or(0);

    // Validate ranges
    if !(1..=12).contains(&month) {
        return Err(format!("month {} out of range [1..12]", month));
    }
    if !(1..=31).contains(&day) {
        return Err(format!("day {} out of range [1..31]", day));
    }
    if hour > 23 {
        return Err(format!("hour {} out of range [0..23]", hour));
    }
    if minute > 59 {
        return Err(format!("minute {} out of range [0..59]", minute));
    }

    Ok((year, month, day, hour, minute))
}

// ─── validate Command ───────────────────────────────────────────────────────

fn cmd_validate(expression: &str, format: OutputFormat) {
    let report = verify_expression(expression);
    if format == OutputFormat::Json {
        let value = serde_json::to_value(&report).unwrap();
        println!("{}", serde_json::to_string_pretty(&value).unwrap());
        return;
    }
    println!("expression: {expression}");
    println!("passed: {}", report.passed);
    println!("diagnostics: {}", report.diagnostics.len());
    for diag in &report.diagnostics {
        println!("  {}: {}", diag.severity, diag.message);
    }
}

// ─── formulas Command ───────────────────────────────────────────────────────

fn cmd_formulas(domain: Option<&str>, limit: usize) {
    let formula_reg = load_formula_registry();

    let formulas: Vec<_> = if let Some(dom) = domain {
        formula_reg.search(dom)
    } else {
        formula_reg.all()
    };

    println!(
        "formulas (showing {} of {}):",
        formulas.len().min(limit),
        formulas.len()
    );
    for f in formulas.iter().take(limit) {
        let inputs = if f.inputs.is_empty() {
            String::new()
        } else {
            format!("{} → ", f.inputs.join(", "))
        };
        println!(
            "  {} [{4:?}]: {}{} = {}",
            f.id, inputs, f.output, f.expression, f.domain
        );
    }
}

// ─── entities Command ───────────────────────────────────────────────────────

fn cmd_entities(filter: Option<&str>, domain: Option<&str>, limit: usize) {
    let entity_reg = load_entity_registry();

    let mut seeds: Vec<_> = if let Some(kw) = filter {
        entity_reg.search_seeds_ref(kw)
    } else {
        entity_reg
            .list_seeds()
            .into_iter()
            .filter_map(|id| entity_reg.get_seed_ref(id))
            .collect()
    };

    if let Some(d) = domain {
        let d = d.to_lowercase();
        seeds.retain(|seed| {
            seed.dominant_graha()
                .map(|g| g.name().to_lowercase().contains(&d))
                .unwrap_or(false)
        });
    }

    println!(
        "entities (showing {} of {}):",
        seeds.len().min(limit),
        seeds.len()
    );
    for seed in seeds.iter().take(limit) {
        let props: Vec<_> = seed.properties.keys().cloned().collect();
        println!(
            "  {} — {} [{}]",
            seed.id,
            seed.description,
            props.join(", ")
        );
    }
}

// ─── optimize Command ────────────────────────────────────────────────────────

/// Canonical, fully-commented `optimize` schema template. Printed by
/// `laverna schema optimize` so a caller (human or LLM) can learn the shape
/// without guessing from Serde errors (T44 / T46). It is itself a valid schema.
const OPTIMIZE_SCHEMA_TEMPLATE: &str = r#"# Laverna `optimize` schema — copy, edit, run:
#   laverna optimize --schema this.toml
#
# Domain-agnostic point/perk allocation solver. It maximizes
# `objective.maximize` (weighted by `objective.weights`) subject to `budget`,
# per-item `cost`, and `requires` prereq gates. Every stat produced by an item
# `effects` MUST appear in a [scoring.*] term, or validation fails loudly.

[meta]
domain = "my_game"        # freeform label
schema_version = 1        # ignored by the solver, kept for audit

[budget]
attribute_points = 22     # pool spent by attribute-type items (cost keys must match)
perk_points = 5           # pool spent by perk-type items

# Items come in two kinds:
#   type = "attribute" -> level 1..=max_level, cost scales per level
#   type = "perk"      -> boolean (level 1), gated by `requires`
[[items]]
id = "technical_ability"
type = "attribute"
cost = { attribute_points = 1 }   # cost PER LEVEL
max_level = 20
effects = { cyberware_capacity = 1.0, tech_dmg_pct = 0.5 }  # stat per level

[[items]]
id = "license_to_chrome_t1"
type = "perk"
requires = ["technical_ability>=15"]   # item_id>=level gate; a cycle is an error
cost = { perk_points = 5 }
effects = { cyberware_stat_mod_pct = 10.0 }

# Objective: maximize a weighted sum of the scores defined below.
# Every entry in `maximize` and every `weights` key MUST name a [scoring.*] table.
[objective]
maximize = ["survivability_score", "control_score"]
weights = { survivability_score = 0.5, control_score = 0.5 }

# Scoring: each score is a linear combination of stats produced by item effects.
[scoring.survivability_score]
terms = { cyberware_capacity = 1.0 }

[scoring.control_score]
terms = { cyberware_stat_mod_pct = 0.2, tech_dmg_pct = 0.1 }
"#;

fn cmd_schema(name: &str) {
    match name {
        "optimize" => print!("{OPTIMIZE_SCHEMA_TEMPLATE}"),
        other => {
            eprintln!("error: unknown schema '{other}' (known: optimize)");
            std::process::exit(2);
        }
    }
}

fn cmd_optimize(schema_path: &str, top_k: usize, explain: bool) {
    let content = match std::fs::read_to_string(schema_path) {
        Ok(c) => c,
        Err(e) => {
            eprintln!("error: cannot read schema '{schema_path}': {e}");
            std::process::exit(2);
        }
    };
    let schema = match laverna::optimize::parse_schema(&content) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("error: {e}");
            std::process::exit(2);
        }
    };
    let solutions = match laverna::optimize::solve(&schema, top_k) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("error: {e}");
            std::process::exit(2);
        }
    };
    for (i, sol) in solutions.iter().enumerate() {
        println!("# solution {} (objective {:.4})", i + 1, sol.objective);
        let mut levels: Vec<(&String, &u32)> = sol.levels.iter().filter(|(_, l)| **l > 0).collect();
        levels.sort_by_key(|(id, _)| id.as_str());
        for (id, l) in levels {
            println!("  {id} = {l}");
        }
        if explain {
            print!("{}", laverna::optimize::explain(&schema, sol));
        }
    }
}

// ─── mcp Command ────────────────────────────────────────────────────────────

#[cfg(feature = "mcp")]
fn cmd_mcp() {
    use std::io::{BufRead, Write};

    eprintln!("laverna mcp: starting JSON-RPC server on stdin/stdout");

    let formula_reg = load_formula_registry();
    let entity_reg = load_entity_registry();
    let forms = load_shikai_forms();
    let events = load_events();

    let descent_engine = DescentEngine::new(formula_reg.clone(), entity_reg.clone(), forms, events);

    let stdin = std::io::stdin();
    let stdout = std::io::stdout();
    let mut reader = stdin.lock();
    let mut writer = stdout.lock();
    let mut buffer = String::new();

    loop {
        buffer.clear();
        match reader.read_line(&mut buffer) {
            Ok(0) => break, // EOF
            Ok(_) => {
                let line = buffer.trim();
                if line.is_empty() {
                    continue;
                }

                // Parse JSON-RPC request
                let response = handle_jsonrpc(line, &descent_engine, &formula_reg, &entity_reg);

                if let Some(resp) = response {
                    let resp_str = serde_json::to_string(&resp).unwrap_or_default();
                    writeln!(writer, "{resp_str}").unwrap();
                    writer.flush().unwrap();
                }
            }
            Err(e) => {
                eprintln!("read error: {e}");
                break;
            }
        }
    }
}

#[cfg(feature = "mcp")]
struct ToolOutput {
    text: String,
    structured: Option<serde_json::Value>,
}

#[cfg(feature = "mcp")]
impl ToolOutput {
    fn text_only(text: String) -> Self {
        ToolOutput {
            text,
            structured: None,
        }
    }
    fn with_structured(text: String, structured: serde_json::Value) -> Self {
        ToolOutput {
            text,
            structured: Some(structured),
        }
    }
}

#[cfg(feature = "mcp")]
fn handle_jsonrpc(
    request: &str,
    descent_engine: &DescentEngine,
    formula_reg: &FormulaRegistry,
    entity_reg: &EntityRegistry,
) -> Option<serde_json::Value> {
    let msg: serde_json::Value = match serde_json::from_str(request) {
        Ok(v) => v,
        Err(_) => {
            return Some(serde_json::json!({
                "jsonrpc": "2.0",
                "error": {"code": -32700, "message": "Parse error"},
                "id": null
            }));
        }
    };

    let method = msg["method"].as_str().unwrap_or("");
    let id = msg["id"].clone();
    let params = &msg["params"];

    match method {
        "initialize" => Some(serde_json::json!({
            "jsonrpc": "2.0",
            "result": {
                "protocolVersion": "2024-11-05",
                "capabilities": {"tools": {"listChanged": false}},
                "serverInfo": {
                    "name": "laverna",
                    "version": env!("CARGO_PKG_VERSION")
                }
            },
            "id": id
        })),
        "notifications/initialized" => None,
        "tools/list" => Some(serde_json::json!({
            "jsonrpc": "2.0",
            "result": {
                "tools": [
                    {
                        "name": "solve",
                        "title": "Laverna Solve",
                        "description": "Run the full deterministic reasoning pipeline on a query: intent + domain classification, 7-layer token descent, and Tanto exact-math evaluation. Use this as the PRIMARY tool for any computation, formula lookup, or cross-domain reasoning. Do NOT use it to fetch a raw entity record (use entity_get) or to generate a birth chart (use chart). Output is exact and reproducible; no values are invented.",
                        "inputSchema": {
                            "type": "object",
                            "properties": {
                                "query": {"type": "string", "description": "Natural-language or structured query to reason about"},
                                "verbose": {"type": "boolean", "description": "Include per-token provenance chains in the result", "default": false}
                            },
                            "required": ["query"]
                        },
                        "outputSchema": {
                            "type": "object",
                            "properties": {
                                "intent": {"type": "string"},
                                "domain": {"type": "string"},
                                "resolution": {"type": "number", "description": "Settlement confidence, 0-100"},
                                "depth": {"type": "number", "description": "Average descent depth, 0-6"},
                                "nand": {"type": "number", "description": "NAND completeness, 0-100"},
                                "tokens": {"type": "array", "items": {
                                    "type": "object",
                                    "properties": {
                                        "text": {"type": "string"},
                                        "layer": {"type": "string"},
                                        "entity": {"type": "string"},
                                        "formal": {"type": "string"},
                                        "value": {"type": "number"}
                                    }
                                }}
                            }
                        },
                        "annotations": {"readOnlyHint": true, "openWorldHint": false, "title": "Laverna Solve"}
                    },
                    {
                        "name": "entity_get",
                        "title": "Laverna Entity Lookup",
                        "description": "Look up a seed entity by exact ID, or search the embedded corpus by keyword. Returns the entity's name, description, and properties, or a ranked list of matches. Use this to inspect a known entity; use solve for reasoning over an entity. Returns only embedded, curated data — never synthesizes new facts.",
                        "inputSchema": {
                            "type": "object",
                            "properties": {
                                "entity_id": {"type": "string", "description": "Entity ID (e.g. \"surya\") or a search keyword"}
                            },
                            "required": ["entity_id"]
                        },
                        "annotations": {"readOnlyHint": true, "openWorldHint": false, "title": "Laverna Entity Lookup"}
                    },
                    {
                        "name": "chart",
                        "title": "Laverna Vedic Chart",
                        "description": "Generate a deterministic Vedic (sidereal/Lahiri) chart for a birth datetime. Pass explicit latitude/longitude, OR a location name that is geocoded to coordinates; lagna and bhavas are only computed when coordinates are available. Use this for chart generation only — use solve for reasoning about chart output. All positions are computed from VSOP87, no network calls.",
                        "inputSchema": {
                            "type": "object",
                            "properties": {
                                "datetime": {"type": "string", "description": "ISO datetime: YYYY-MM-DD HH:MM:SS"},
                                "location": {"type": "string", "description": "Location name (geocoded to coordinates; drives lagna + bhavas)"},
                                "latitude": {"type": "number", "description": "Observer latitude in degrees (N positive)"},
                                "longitude": {"type": "number", "description": "Observer longitude in degrees (E positive)"}
                            },
                            "required": ["datetime"]
                        },
                        "outputSchema": {
                            "type": "object",
                            "properties": {
                                "julian_day": {"type": "number"},
                                "ayanamsa": {"type": "number"},
                                "lagna": {"type": "string"},
                                "bhavas": {"type": "array", "items": {
                                    "type": "object",
                                    "properties": {
                                        "house": {"type": "string"},
                                        "tropical": {"type": "number"},
                                        "rashi": {"type": "string"}
                                    }
                                }},
                                "grahas": {"type": "array", "items": {
                                    "type": "object",
                                    "properties": {
                                        "name": {"type": "string"},
                                        "tropical": {"type": "number"},
                                        "sidereal": {"type": "number"},
                                        "rashi": {"type": "string"},
                                        "degree_in_sign": {"type": "number"}
                                    }
                                }}
                            }
                        },
                        "annotations": {"readOnlyHint": true, "openWorldHint": false, "title": "Laverna Vedic Chart"}
                    },
                    {
                        "name": "validate",
                        "title": "Laverna Validate",
                        "description": "Validate a mathematical or logical expression and return a structured diagnostic report (passed flag + per-issue severity/message). Use this to check a formula or expression before trusting it. Does not evaluate to a final number — use solve for that.",
                        "inputSchema": {
                            "type": "object",
                            "properties": {
                                "expression": {"type": "string", "description": "Expression to validate"}
                            },
                            "required": ["expression"]
                        },
                        "outputSchema": {
                            "type": "object",
                            "properties": {
                                "expression": {"type": "string"},
                                "passed": {"type": "boolean"},
                                "diagnostics": {"type": "array", "items": {
                                    "type": "object",
                                    "properties": {
                                        "severity": {"type": "string"},
                                        "message": {"type": "string"}
                                    }
                                }}
                            }
                        },
                        "annotations": {"readOnlyHint": true, "openWorldHint": false, "title": "Laverna Validate"}
                    },
                    {
                        "name": "formulas",
                        "title": "Laverna Formula List",
                        "description": "Search the embedded formula corpus by domain keyword, or list all formulas. Use this for discovery of available relationships; prefer solve to actually apply a formula. Pass 'limit' to cap output for token efficiency.",
                        "inputSchema": {
                            "type": "object",
                            "properties": {
                                "domain": {"type": "string", "description": "Filter by domain keyword (empty = all)"},
                                "limit": {"type": "integer", "description": "Max results returned", "default": 20}
                            }
                        },
                        "annotations": {"readOnlyHint": true, "openWorldHint": false, "title": "Laverna Formula List"}
                    },
                    {
                        "name": "entities",
                        "title": "Laverna Entity List",
                        "description": "List seed entities from the embedded corpus, optionally filtered by keyword. Use this for corpus discovery; prefer entity_get for a single known entity. Pass 'limit' to cap output for token efficiency.",
                        "inputSchema": {
                            "type": "object",
                            "properties": {
                                "filter": {"type": "string", "description": "Filter by keyword (empty = all)"},
                                "limit": {"type": "integer", "description": "Max results returned", "default": 20}
                            }
                        },
                        "annotations": {"readOnlyHint": true, "openWorldHint": false, "title": "Laverna Entity List"}
                    },
                    {
                        "name": "optimize",
                        "title": "Laverna Optimize",
                        "description": "Solve a domain-agnostic stat/point-allocation optimization from a TOML schema (see 'laverna schema optimize' for the shape). Returns top-K Pareto-optimal allocations. Use this only for allocation/optimization problems expressible in the schema; use solve for general reasoning.",
                        "inputSchema": {
                            "type": "object",
                            "properties": {
                                "schema_path": {"type": "string", "description": "Path to the TOML optimization schema"},
                                "top_k": {"type": "integer", "description": "Return N distinct Pareto-optimal allocations", "default": 1},
                                "explain": {"type": "boolean", "description": "Include the per-item marginal-value trace", "default": false}
                            },
                            "required": ["schema_path"]
                        },
                        "annotations": {"readOnlyHint": true, "openWorldHint": false, "title": "Laverna Optimize"}
                    }
                ]
            },
            "id": id
        })),
        "tools/call" => {
            let tool_name = params["name"].as_str().unwrap_or("");
            let args = &params["arguments"];

            let result = match tool_name {
                "solve" => {
                    let query = args["query"].as_str().unwrap_or("");
                    let verbose = args["verbose"].as_bool().unwrap_or(false);
                    solve_tool(query, verbose, descent_engine)
                }
                "entity_get" => {
                    let entity_id = args["entity_id"].as_str().unwrap_or("");
                    entity_get_tool(entity_id, entity_reg)
                }
                "chart" => {
                    let datetime = args["datetime"].as_str().unwrap_or("2000-01-01 12:00:00");
                    let location = args["location"].as_str();
                    let latitude = args["latitude"].as_f64();
                    let longitude = args["longitude"].as_f64();
                    chart_tool(datetime, location, latitude, longitude)
                }
                "validate" => {
                    let expression = args["expression"].as_str().unwrap_or("");
                    validate_tool(expression)
                }
                "formulas" => {
                    let domain = args["domain"].as_str();
                    let limit = args["limit"].as_u64().unwrap_or(20) as usize;
                    formulas_tool(domain, limit, formula_reg)
                }
                "entities" => {
                    let filter = args["filter"].as_str();
                    let limit = args["limit"].as_u64().unwrap_or(20) as usize;
                    entities_tool(filter, limit, entity_reg)
                }
                "optimize" => {
                    let schema_path = args["schema_path"].as_str().unwrap_or("");
                    let top_k = args["top_k"].as_u64().unwrap_or(1) as usize;
                    let explain = args["explain"].as_bool().unwrap_or(false);
                    optimize_tool(schema_path, top_k, explain)
                }
                _ => Err(format!("unknown tool: {tool_name}")),
            };

            match result {
                Ok(output) => {
                    let mut result_obj = serde_json::json!({
                        "content": [{"type": "text", "text": output.text}]
                    });
                    if let Some(structured) = output.structured {
                        result_obj["structuredContent"] = structured;
                    }
                    Some(serde_json::json!({
                        "jsonrpc": "2.0",
                        "result": result_obj,
                        "id": id
                    }))
                }
                Err(error) => Some(serde_json::json!({
                    "jsonrpc": "2.0",
                    "result": {
                        "content": [{"type": "text", "text": format!("error: {error}")}],
                        "isError": true
                    },
                    "id": id
                })),
            }
        }
        "ping" => Some(serde_json::json!({
            "jsonrpc": "2.0",
            "result": "pong",
            "id": id
        })),
        _ => Some(serde_json::json!({
            "jsonrpc": "2.0",
            "error": {"code": -32601, "message": format!("method not found: {method}")},
            "id": id
        })),
    }
}

#[cfg(feature = "mcp")]
fn solve_tool(query: &str, verbose: bool, engine: &DescentEngine) -> Result<ToolOutput, String> {
    let mut out = String::new();
    let intent = laverna::shikai::parse_query_intent(query);
    let domain = laverna::shikai::determine_query_domain(query);
    out.push_str(&format!("intent: {intent}\ndomain: {domain}\n\n"));

    let matrix = engine.descend(query);
    out.push_str(&format!(
        "resolution: {:.0}%, depth: {:.2}/6, nand: {:.0}%\n\n",
        matrix.resolution_score * 100.0,
        matrix.average_depth,
        matrix.nand_completeness() * 100.0,
    ));

    for token in &matrix.tokens {
        out.push_str(&format!(
            "\"{}\" → {} (d{})",
            token.text,
            token.settled_layer.name(),
            token.settled_layer.depth(),
        ));
        if let Some(ref entity) = token.entity {
            out.push_str(&format!(", entity: {entity}"));
        }
        if let Some(ref expr) = token.formal_expression {
            out.push_str(&format!(", formal: \"{expr}\""));
            let env = create_env();
            if let Some(val) = evaluate_expr(expr, &env) {
                out.push_str(&format!(" = {val:.4}"));
            }
        }
        out.push('\n');
    }

    if verbose {
        out.push_str("\nprovenance:\n");
        for token in &matrix.tokens {
            if !token.provenance.is_empty() {
                out.push_str(&format!(
                    "  \"{}\": {} steps\n",
                    token.text,
                    token.provenance.len()
                ));
            }
        }
    }

    let mut tokens_json = Vec::new();
    for token in &matrix.tokens {
        let mut token_json = serde_json::json!({
            "text": token.text,
            "layer": token.settled_layer.name()
        });
        if let Some(ref entity) = token.entity {
            token_json["entity"] = serde_json::json!(entity);
        }
        if let Some(ref expr) = token.formal_expression {
            token_json["formal"] = serde_json::json!(expr);
            let env = create_env();
            if let Some(value) = evaluate_expr(expr, &env) {
                token_json["value"] = serde_json::json!(value);
            }
        }
        tokens_json.push(token_json);
    }
    let structured = serde_json::json!({
        "intent": intent,
        "domain": domain,
        "resolution": matrix.resolution_score * 100.0,
        "depth": matrix.average_depth,
        "nand": matrix.nand_completeness() * 100.0,
        "tokens": tokens_json
    });
    Ok(ToolOutput::with_structured(out, structured))
}

#[cfg(feature = "mcp")]
fn entity_get_tool(entity_id: &str, reg: &EntityRegistry) -> Result<ToolOutput, String> {
    if let Some(seed) = reg.get_seed_ref(entity_id) {
        let mut out = format!(
            "id: {}\nname: {}\ndescription: {}\n",
            seed.id, seed.name, seed.description
        );
        if !seed.properties.is_empty() {
            out.push_str("properties:\n");
            let mut props: Vec<_> = seed.properties.iter().collect();
            props.sort_by_key(|(a, _)| *a);
            for (k, v) in props {
                out.push_str(&format!("  {k}: {v}\n"));
            }
        }
        Ok(ToolOutput::text_only(out))
    } else {
        let results = reg.search_seeds_ref(entity_id);
        if results.is_empty() {
            Err(format!("entity not found: {entity_id}"))
        } else {
            let mut out = format!("search results for \"{entity_id}\":\n");
            for s in &results {
                out.push_str(&format!("  {} — {}\n", s.id, s.description));
            }
            Ok(ToolOutput::text_only(out))
        }
    }
}

#[cfg(feature = "mcp")]
fn chart_tool(
    datetime: &str,
    location: Option<&str>,
    latitude: Option<f64>,
    longitude: Option<f64>,
) -> Result<ToolOutput, String> {
    let dt = parse_datetime(datetime)?;
    let jd = julian_day(
        dt.0 as i16,
        dt.1 as u8,
        dt.2 as u8,
        dt.3 as f64 + dt.4 as f64 / 60.0,
    );
    let ayanamsa = lahiri_ayanamsa(jd);

    let mut out = format!("julian_day: {jd:.4}\nayanamsa: {ayanamsa:.4}°\n\n");

    // Resolve observer coordinates for lagna + bhavas.
    let coords: Option<(f64, f64)> = if let Some((lat, lon)) = latitude.zip(longitude) {
        validate_chart_coords(lat, lon)?;
        Some((lat, lon))
    } else if let Some(loc) = location {
        geocode_city(loc)
    } else {
        None
    };

    let mut chart = ChartSnapshot::new(jd);
    if let Some((lat, lon)) = coords {
        chart = chart.with_location(lat, lon);
    }

    let lagna_name: Option<String> = chart.lagna.map(|l| l.name().to_string());
    if let Some(lagna) = chart.lagna {
        let extra = chart
            .ascendant_deg
            .map(|d| format!("  —  {d:.4}° sidereal"))
            .unwrap_or_default();
        out.push_str(&format!("lagna: {} ({:?}){}\n", lagna.name(), lagna, extra));
    }

    let mut bhavas_json = Vec::new();
    if !chart.house_cusps.is_empty() {
        out.push_str("\nbhavas:\n");
        for cusp in &chart.house_cusps {
            out.push_str(&format!(
                "  {:>5}: {:>8.2}° {:10}\n",
                cusp.house.name(),
                cusp.tropical,
                cusp.rashi.name(),
            ));
            bhavas_json.push(serde_json::json!({
                "house": cusp.house.name(),
                "tropical": cusp.tropical,
                "rashi": cusp.rashi.name()
            }));
        }
        out.push('\n');
    }

    let graha_names = [
        "Surya",
        "Chandra",
        "Mangala",
        "Budha",
        "Brihaspati",
        "Shukra",
        "Shani",
        "Rahu",
        "Ketu",
    ];

    out.push_str("grahas:\n");
    let mut grahas_json = Vec::new();
    for (i, name) in graha_names.iter().enumerate() {
        let gp = laverna::ephemeris::graha_position(Graha::from_index(i).unwrap(), jd);
        let degree_in_sign = gp.sidereal % 30.0;
        out.push_str(&format!(
            "{name:>12}: tropical {:>7.2}°, sidereal {:>7.2}° ({:?} {degree_in_sign:.2}°)\n",
            gp.tropical, gp.sidereal, gp.rashi
        ));
        grahas_json.push(serde_json::json!({
            "name": name,
            "tropical": gp.tropical,
            "sidereal": gp.sidereal,
            "rashi": gp.rashi.name(),
            "degree_in_sign": degree_in_sign
        }));
    }

    let structured = serde_json::json!({
        "julian_day": jd,
        "ayanamsa": ayanamsa,
        "lagna": lagna_name,
        "bhavas": bhavas_json,
        "grahas": grahas_json
    });
    Ok(ToolOutput::with_structured(out, structured))
}

#[cfg(feature = "mcp")]
fn validate_tool(expression: &str) -> Result<ToolOutput, String> {
    let report = verify_expression(expression);
    let mut out = format!(
        "expression: {expression}\npassed: {}\ndiagnostics: {}\n",
        report.passed,
        report.diagnostics.len()
    );
    let mut diagnostics_json = Vec::new();
    for diag in &report.diagnostics {
        out.push_str(&format!("  {}: {}\n", diag.severity, diag.message));
        diagnostics_json.push(serde_json::json!({
            "severity": format!("{:?}", diag.severity),
            "message": diag.message
        }));
    }
    let structured = serde_json::json!({
        "expression": expression,
        "passed": report.passed,
        "diagnostics": diagnostics_json
    });
    Ok(ToolOutput::with_structured(out, structured))
}

#[cfg(feature = "mcp")]
fn formulas_tool(
    domain: Option<&str>,
    limit: usize,
    reg: &FormulaRegistry,
) -> Result<ToolOutput, String> {
    let formulas = if let Some(dom) = domain {
        reg.search(dom)
    } else {
        reg.all()
    };
    let mut out = format!(
        "formulas ({} of {}):\n",
        formulas.len().min(limit),
        formulas.len()
    );
    for f in formulas.iter().take(limit) {
        let inputs = if f.inputs.is_empty() {
            String::new()
        } else {
            format!("{} → ", f.inputs.join(", "))
        };
        out.push_str(&format!(
            "  {} [{:?}]: {}{} = {}\n",
            f.id, f.domain, inputs, f.output, f.expression
        ));
    }
    Ok(ToolOutput::text_only(out))
}

#[cfg(feature = "mcp")]
fn entities_tool(
    filter: Option<&str>,
    limit: usize,
    reg: &EntityRegistry,
) -> Result<ToolOutput, String> {
    let seeds: Vec<_> = if let Some(kw) = filter {
        reg.search_seeds_ref(kw)
    } else {
        reg.list_seeds()
            .into_iter()
            .filter_map(|id| reg.get_seed_ref(id))
            .collect()
    };
    let mut out = format!(
        "entities ({} of {}):\n",
        seeds.len().min(limit),
        seeds.len()
    );
    for s in seeds.iter().take(limit) {
        let props: Vec<_> = s.properties.keys().cloned().collect();
        out.push_str(&format!(
            "  {} — {} [{}]\n",
            s.id,
            s.description,
            props.join(", ")
        ));
    }
    Ok(ToolOutput::text_only(out))
}

#[cfg(feature = "mcp")]
fn optimize_tool(schema_path: &str, top_k: usize, explain: bool) -> Result<ToolOutput, String> {
    let content = std::fs::read_to_string(schema_path)
        .map_err(|e| format!("cannot read schema '{schema_path}': {e}"))?;
    let schema = laverna::optimize::parse_schema(&content)?;
    let solutions = laverna::optimize::solve(&schema, top_k)?;
    let mut out = String::new();
    for (i, sol) in solutions.iter().enumerate() {
        out.push_str(&format!(
            "# solution {} (objective {:.4})\n",
            i + 1,
            sol.objective
        ));
        let mut levels: Vec<(&String, &u32)> = sol.levels.iter().filter(|(_, l)| **l > 0).collect();
        levels.sort_by_key(|(id, _)| id.as_str());
        for (id, l) in levels {
            out.push_str(&format!("  {id} = {l}\n"));
        }
        if explain {
            out.push_str(&laverna::optimize::explain(&schema, sol));
        }
    }
    Ok(ToolOutput::text_only(out))
}

// ─── websearch Command ──────────────────────────────────────────────────────

#[cfg(feature = "websearch")]
const WB_INDICATORS: &[(&str, &str)] = &[
    ("gdp per capita", "NY.GDP.PCAP.CD"),
    ("gdp growth", "NY.GDP.MKTP.KD.ZG"),
    ("gdp ppp", "NY.GDP.MKTP.PP.CD"),
    ("gdp", "NY.GDP.MKTP.CD"),
    ("population", "SP.POP.TOTL"),
    ("unemployment", "SL.UEM.TOTL.ZS"),
    ("life expectancy", "SP.DYN.LE00.IN"),
    ("inflation", "FP.CPI.TOTL.ZG"),
    ("co2", "EN.ATM.CO2E.KT"),
    ("fertility", "SP.DYN.TFRT.IN"),
];

#[cfg(feature = "websearch")]
const WB_COUNTRIES: &[(&str, &str)] = &[
    ("united states", "US"),
    ("usa", "US"),
    ("us", "US"),
    ("world", "WLD"),
    ("global", "WLD"),
    ("china", "CN"),
    ("india", "IN"),
    ("japan", "JP"),
    ("germany", "DE"),
    ("france", "FR"),
    ("united kingdom", "GB"),
    ("uk", "GB"),
    ("britain", "GB"),
    ("brazil", "BR"),
    ("russia", "RU"),
    ("canada", "CA"),
    ("australia", "AU"),
    ("mexico", "MX"),
    ("indonesia", "ID"),
    ("nigeria", "NG"),
];

#[cfg(feature = "websearch")]
fn resolve_country_alias(name: &str) -> String {
    let n = name.trim().to_lowercase();
    if n.is_empty() {
        return "WLD".to_string();
    }
    for (alias, code) in WB_COUNTRIES {
        if n == *alias {
            return code.to_string();
        }
    }
    n.to_uppercase()
}

/// Pure: parse a free-form websearch query into (indicator code, country, year).
#[cfg(feature = "websearch")]
fn parse_websearch_query(query: &str) -> (String, String, Option<u32>) {
    let mut year: Option<u32> = None;
    let mut kept: Vec<&str> = Vec::new();
    for token in query.split_whitespace() {
        if let Ok(y) = token.parse::<u32>() {
            if (1900..=2100).contains(&y) {
                year = Some(y);
                continue;
            }
        }
        kept.push(token);
    }
    let rest = kept.join(" ");
    let rest_lower = rest.to_lowercase();

    let mut indicator: Option<String> = None;
    let mut country_part = rest.clone();
    for (alias, code) in WB_INDICATORS {
        if rest_lower.starts_with(*alias) {
            indicator = Some(code.to_string());
            country_part = rest[alias.len()..].trim().to_string();
            break;
        }
    }
    if indicator.is_none() {
        if let Some((first, remainder)) = rest.split_once(' ') {
            indicator = Some(first.to_string());
            country_part = remainder.trim().to_string();
        } else {
            indicator = Some(rest.clone());
            country_part = String::new();
        }
    }
    let country = resolve_country_alias(&country_part);
    (indicator.unwrap(), country, year)
}

/// Pure: extract the most recent non-null observation from a World Bank JSON body.
#[cfg(feature = "websearch")]
fn parse_world_bank_response(body: &str) -> Result<String, String> {
    let value: serde_json::Value =
        serde_json::from_str(body).map_err(|e| format!("invalid World Bank JSON: {e}"))?;
    let observations = value
        .get(1)
        .and_then(|a| a.as_array())
        .ok_or_else(|| "World Bank response had no observation array".to_string())?;
    let mut chosen: Option<&serde_json::Value> = None;
    for obs in observations {
        if obs.get("value").and_then(|v| v.as_f64()).is_some() {
            chosen = Some(obs);
        }
    }
    let obs = chosen.ok_or_else(|| "no non-null observations returned".to_string())?;
    let indicator = obs
        .get("indicator")
        .and_then(|i| i.get("value"))
        .and_then(|v| v.as_str())
        .unwrap_or("?");
    let country = obs
        .get("country")
        .and_then(|c| c.get("value"))
        .and_then(|v| v.as_str())
        .unwrap_or("?");
    let date = obs.get("date").and_then(|d| d.as_str()).unwrap_or("?");
    let val = obs
        .get("value")
        .and_then(|v| v.as_f64())
        .ok_or_else(|| "missing value".to_string())?;
    Ok(format!("{indicator} — {country} ({date}): {val}"))
}

#[cfg(feature = "websearch")]
fn world_bank_lookup(indicator: &str, country: &str, year: Option<u32>) -> Result<String, String> {
    let date = match year {
        Some(y) => y.to_string(),
        None => "2015:2024".to_string(),
    };
    let url = format!(
        "https://api.worldbank.org/v2/country/{country}/indicator/{indicator}?format=json&date={date}&per_page=20"
    );
    let agent = ureq::AgentBuilder::new().build();
    let response = agent
        .get(&url)
        .call()
        .map_err(|e| format!("World Bank request failed: {e}"))?;
    let body = response
        .into_string()
        .map_err(|e| format!("read World Bank body failed: {e}"))?;
    parse_world_bank_response(&body)
}

#[cfg(feature = "websearch")]
fn cmd_websearch(query: &str) {
    let (indicator, country, year) = parse_websearch_query(query);
    eprintln!("websearch: indicator={indicator} country={country} year={year:?}");
    match world_bank_lookup(&indicator, &country, year) {
        Ok(line) => println!("{line}"),
        Err(e) => {
            eprintln!("websearch error: {e}");
            std::process::exit(1);
        }
    }
}

#[cfg(all(test, feature = "websearch"))]
mod websearch_tests {
    use super::*;

    #[test]
    fn parses_gdp_us_year() {
        let (ind, c, y) = parse_websearch_query("gdp united states 2020");
        assert_eq!(ind, "NY.GDP.MKTP.CD");
        assert_eq!(c, "US");
        assert_eq!(y, Some(2020));
    }

    #[test]
    fn parses_population_world_no_year() {
        let (ind, c, y) = parse_websearch_query("population");
        assert_eq!(ind, "SP.POP.TOTL");
        assert_eq!(c, "WLD");
        assert_eq!(y, None);
    }

    #[test]
    fn parses_raw_indicator_and_country() {
        let (ind, c, _y) = parse_websearch_query("SP.DYN.LE00.IN japan");
        assert_eq!(ind, "SP.DYN.LE00.IN");
        assert_eq!(c, "JP");
    }

    #[test]
    fn parses_response_offline() {
        let body = r#"[{"page":1},[{"indicator":{"id":"NY.GDP.MKTP.CD","value":"GDP (current US$)"},"country":{"id":"US","value":"United States"},"date":"2020","value":21375281000000}]]"#;
        let line = parse_world_bank_response(body).unwrap();
        assert!(line.contains("United States"));
        assert!(line.contains("2020"));
        assert!(line.contains("21375281000000"));
    }
}

#[cfg(test)]
mod t36_tests {
    use super::*;

    #[test]
    fn extracts_operator_expression_with_precedence() {
        // "2 + 3 * 4" must evaluate to 14, not naive (2+3)=5 then (3*4)...
        let expr = extract_arithmetic_expression("what is 2 + 3 * 4?").expect("expr");
        let env = create_env();
        let val = evaluate_expr(&expr, &env).expect("eval");
        assert!((val - 14.0).abs() < 1e-9, "expected 14, got {val}");
    }

    #[test]
    fn extracts_equation_and_splits_lhs() {
        let expr = extract_arithmetic_expression("verify 2 + 3 = 5").expect("expr");
        assert!(expr.contains('='));
        let env = create_env();
        let eq = expr.find('=').unwrap();
        let lhs = &expr[..eq];
        let val = evaluate_expr(lhs, &env).expect("eval lhs");
        assert!((val - 5.0).abs() < 1e-9, "expected 5, got {val}");
    }

    #[test]
    fn modulo_keeps_first_operand() {
        // T42 regression: "%" must not drop the left operand.
        // "10 % 3 = 1" must evaluate to 1.0 and match stated RHS.
        let expr = extract_arithmetic_expression("10 % 3 = 1").expect("expr");
        assert!(expr.contains('%'), "expr dropped modulo: {expr:?}");
        let env = create_env();
        let eq = expr.find('=').unwrap();
        let lhs = &expr[..eq];
        let val = evaluate_expr(lhs, &env).expect("eval lhs");
        assert!((val - 1.0).abs() < 1e-9, "expected 1, got {val}");
        let rhs: f64 = expr[eq + 1..].trim().parse().unwrap();
        assert!((val - rhs).abs() < 1e-9, "lhs {val} != rhs {rhs}");
    }

    #[test]
    fn no_arithmetic_returns_none() {
        assert!(extract_arithmetic_expression("the cat sat on the mat").is_none());
    }

    #[test]
    fn strips_trailing_operator() {
        let expr = extract_arithmetic_expression("compute 2 + 3 =").expect("expr");
        assert!(!expr.ends_with('='), "expr was {expr:?}");
        let env = create_env();
        assert!((evaluate_expr(&expr, &env).unwrap() - 5.0).abs() < 1e-9);
    }
}
